# Generated by Django 5.2.8 on 2025-12-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_reorder_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reorder_level',
        ),
    ]
