# Generated by Django 5.2.8 on 2025-12-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_item_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_bar',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
